# Author: Zhongkai Fu (fuzhongkai@gmail.com)
# License: BSD 3-Clause License

"""Lightweight compatibility layer for the OpenAI Agent SDK.

The planner prefers to import the official ``agents`` package that ships
``Agent``, ``Runner`` and ``function_tool``. When that package is not
available (for example in minimal CI environments), we fall back to a
shim that mirrors the same interface on top of Chat Completions. The shim
intentionally strips ``additionalProperties`` from generated JSON Schemas
to avoid the OpenAI Agents service rejecting tools with strict object
schemas.
"""

from __future__ import annotations

import inspect
import json
import os
from dataclasses import dataclass
from typing import Any, Callable, Dict, Iterable, List, Mapping, MutableMapping, Sequence

from openai import OpenAI
from pydantic import create_model

try:  # pragma: no cover - exercised indirectly via planner integration tests
    from agents import Agent as _Agent
    from agents import Runner as _Runner
    from agents import function_tool as _function_tool
except Exception:  # noqa: BLE001 - fall back to shim when the SDK is unavailable
    _Agent = None
    _Runner = None
    _function_tool = None


def _strip_additional_properties(schema: Any) -> Any:
    """Recursively drop ``additionalProperties`` keys from JSON Schemas.

    The OpenAI Agents service rejects object schemas that explicitly set
    ``additionalProperties``. Some ecosystem packages (notably Pydantic 1.x)
    emit that flag by default, which triggers ``ensure_strict_json_schema`` to
    raise. This helper sanitizes schemas generated by the compatibility shim.
    """

    if isinstance(schema, dict):
        return {
            key: _strip_additional_properties(value)
            for key, value in schema.items()
            if key != "additionalProperties"
        }
    if isinstance(schema, list):
        return [_strip_additional_properties(item) for item in schema]
    return schema


def function_tool(func: Callable | None = None, **kwargs: Any):
    """Decorate functions as tools while avoiding strict schemas.

    When the official ``agents`` SDK is available, this wrapper forwards to
    its ``function_tool`` decorator but forces ``strict_schema=False`` when the
    parameter is supported. This sidesteps the ``additionalProperties`` error
    highlighted in the runtime stack traces. When the SDK is missing, a
    lightweight shim is used instead; it records the original callable on the
    wrapper so the planner can still call the tool functions directly.
    """

    def _decorate(target: Callable):
        if _function_tool is None:
            target._tool_fn = target  # type: ignore[attr-defined]
            target._tool_schema = None  # type: ignore[attr-defined]
            return target

        try:
            sig = inspect.signature(_function_tool)
            accepts_strict = "strict_schema" in sig.parameters
        except (TypeError, ValueError):
            accepts_strict = False

        if accepts_strict:
            kwargs.setdefault("strict_schema", False)
        else:
            kwargs.pop("strict_schema", None)

        # Drop any kwargs the installed SDK version does not accept to stay
        # compatible across releases.
        try:
            accepted = inspect.signature(_function_tool).parameters
            filtered_kwargs = {k: v for k, v in kwargs.items() if k in accepted}
        except (TypeError, ValueError):
            filtered_kwargs = kwargs

        return _function_tool(target, **filtered_kwargs)

    if func is None:
        return _decorate
    return _decorate(func)


if _Agent is not None and _Runner is not None:
    Agent = _Agent
    Runner = _Runner
else:  # pragma: no cover - shim used only when ``agents`` is unavailable

    @dataclass
    class Agent:
        instructions: str
        tools: Sequence[Callable]
        model: str

    class Runner:
        @staticmethod
        def run(agent: Agent, run_input: Any, **_: Any):
            raise RuntimeError(
                "The 'agents' package is not installed; install it to enable Agent SDK execution."
            )

    def _build_schema_from_callable(func: Callable) -> Dict[str, Any]:
        sig = inspect.signature(func)
        annotations = {name: param.annotation for name, param in sig.parameters.items() if name != "self"}
        defaults = {name: param.default for name, param in sig.parameters.items() if param.default is not param.empty}

        model = create_model(
            func.__name__ + "Params",
            **{name: (annotations.get(name, Any), defaults.get(name, ...)) for name in annotations},
        )
        schema = model.model_json_schema()
        return _strip_additional_properties(schema)

    def build_tool_call(payload: Mapping[str, Any]) -> Dict[str, Any]:
        tool_name = payload.get("type")
        tool_input = payload.get("input")
        for tool in payload.get("tools", []):
            if getattr(tool, "__name__", None) == tool_name:
                fn = getattr(tool, "_tool_fn", tool)
                return fn(**tool_input)
        raise ValueError(f"Unknown tool {tool_name}")
